### ISSUE TITLE
Long-press Bottom Sheet Menu Issues

### ISSUE THREAD

**Issue by lance-zigazoo** [cometchat-pro/cometchat-chat-uikit-react-native#51]
### Describe the problem

> Long-press menu does not work consistently:
When interacting with the long-press menu on a message bubble, image, video, etc. a bottom sheet is presented to the user on the screen.  Many times, the bottom sheet's rendered items do not appear, e.g. the "Delete", "Start a thread" and other messages.  Additionally after several attempts (depends on device) a noticeable performance degradation takes place, e.g. the menu animation begins to slow substantially, and interacting with the chat components leaves much to be desired in the way of performance.

### What was the expected behavior?

> I expect the experience to be consistent (menu content renders every time), and I expect that the performance of the application is not affected by using the long-press / bottom sheet menu functionality.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

(android emulator an iOS devices seem to suffer the problem the most)

1. Open a chat
2. Send a message
3. Long press on the message bubble to summon the action menu
4. Dismiss action menu
5. Repeat several times

[Android Example (kitchen sink app cloned from CCPro repo)](https://drive.google.com/file/d/1PWRElojMcmb4WtzAoRq8OFppLeYt2bVV/view?usp=share_link)
[iOS Example (using rn toolkit in our app)](https://drive.google.com/file/d/1QxUsLz-BWorSBGG-gjOHqX9me0cAqc4J/view?usp=share_link)

The code flow appears to be: Long press chat bubble in [CometChatSenderImageMessageBubble](https://github.com/cometchat-pro/cometchat-pro-react-native-ui-kit/blob/master/CometChatWorkspace/src/components/Messages/CometChatSenderImageMessageBubble/index.js#L76) -> [CometChatMessage](https://github.com/cometchat-pro/cometchat-pro-react-native-ui-kit/blob/master/CometChatWorkspace/src/components/Messages/CometChatMessages/index.js#L339) -> [Close](https://github.com/cometchat-pro/cometchat-pro-react-native-ui-kit/blob/master/CometChatWorkspace/src/components/Messages/CometChatMessages/index.js#L1111) -> [CometChatMessageActions](https://github.com/cometchat-pro/cometchat-pro-react-native-ui-kit/blob/master/CometChatWorkspace/src/components/Messages/CometChatMessageActions/index.js#L17) -> [CometChatMessageActions/actions](https://github.com/cometchat-pro/cometchat-pro-react-native-ui-kit/blob/master/CometChatWorkspace/src/components/Messages/CometChatMessageActions/actions.js#L23)

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

For the above points, your Kitchen Sink app exhibits the behavior as-is.

### Environment

> Please provide the following:

- **Version used:**
- [cometchat-pro-react-native-ui-kit-v3.0.6-4](https://github.com/cometchat-pro/cometchat-pro-react-native-ui-kit/releases/tag/V3.0.6-4)
- @cometchat-pro/react-native-chat": "3.0.6"

- **Other modules/plugins/libraries that might be involved:**

**Comment by proveshapyne** [comment]
Hey @lance-zigazoo,

Thanks for sharing these details. We're investigating and will reach out with an update shortly.

Provesha Pyne
CometChat

**Comment by lance-zigazoo** [comment]
Hi Provesha, it is a Comet Chat repo, you should have access to it.

**Comment by lance-zigazoo** [comment]
I may have cloned it, in which case, you should be able to just use the
root project.

**Comment by lance-zigazoo** [comment]
Hi Provesha,

Thank you for the message.

Please find the AVD here
<https://drive.google.com/file/d/1vYcPIHma2ZuXOd6KDQEkKYq_7KWDDPRm/view?usp=share_link>
.

At this point, our team believes that we have provided enough materials and
anecdotal evidence to assist in the debugging process, however results have
not been delivered yet.
We have a critical application release coming up that includes the use of
Comet Chat, and our deadlines are not flexible.  I would like to
request that you assign an engineer to work with me in real-time to come
bring this issue to a speedy resolution.

Please let me know what we can arrange at your earliest convenience.

Regards,

Lance

**Comment by lance-zigazoo** [comment]
Thank you Keagan and Juhi,

A minor point of clarification is that this is not isolated to iOS, however
it it more easily reproduced on that platform, at least in our case.  There
is a call to onCloseEnd that seems to be triggered unexpectedly at times.

Regards,

Lance

**Comment by jasimawan** [comment]
How can I disable the long press bottom sheet?
